# Generated by Django 4.2.2 on 2023-06-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreE', models.CharField(max_length=30)),
                ('tipoE', models.CharField(max_length=30)),
                ('stockE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ferreteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreF', models.CharField(max_length=30)),
                ('tipoF', models.CharField(max_length=30)),
                ('stockF', models.IntegerField()),
            ],
        ),
    ]
