# Generated by Django 4.2.2 on 2023-06-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epp',
            old_name='nombreE',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='epp',
            old_name='stockE',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='epp',
            old_name='tipoE',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='ferreteria',
            old_name='nombreF',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ferreteria',
            old_name='stockF',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='ferreteria',
            old_name='tipoF',
            new_name='tipo',
        ),
    ]
